/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherTimetableRouteImport } from './routes/teacher.timetable'
import { Route as TeacherRoomRequestRouteImport } from './routes/teacher.room-request'
import { Route as TeacherResultsRouteImport } from './routes/teacher.results'
import { Route as TeacherProfileRouteImport } from './routes/teacher.profile'
import { Route as TeacherNoticesRouteImport } from './routes/teacher.notices'
import { Route as TeacherMessagesRouteImport } from './routes/teacher.messages'
import { Route as TeacherLeaveRouteImport } from './routes/teacher.leave'
import { Route as TeacherGradebookRouteImport } from './routes/teacher.gradebook'
import { Route as TeacherDashboardRouteImport } from './routes/teacher.dashboard'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as StudentTimetableRouteImport } from './routes/student.timetable'
import { Route as StudentResultsRouteImport } from './routes/student.results'
import { Route as StudentNoticesRouteImport } from './routes/student.notices'
import { Route as StudentMessagesRouteImport } from './routes/student.messages'
import { Route as StudentLibraryRouteImport } from './routes/student.library'
import { Route as StudentFeesRouteImport } from './routes/student.fees'
import { Route as StudentFeedbackRouteImport } from './routes/student.feedback'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentEventsRouteImport } from './routes/student.events'
import { Route as StudentDocumentsRouteImport } from './routes/student.documents'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentAttendanceRouteImport } from './routes/student.attendance'
import { Route as StudentActivityRouteImport } from './routes/student.activity'
import { Route as AdminTimetableRouteImport } from './routes/admin.timetable'
import { Route as AdminTeachersRouteImport } from './routes/admin.teachers'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminRoomApprovalsRouteImport } from './routes/admin.room-approvals'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminExamsRouteImport } from './routes/admin.exams'
import { Route as AdminEnrollmentRouteImport } from './routes/admin.enrollment'
import { Route as AdminDocumentRequestsRouteImport } from './routes/admin.document-requests'
import { Route as AdminDepartmentsRouteImport } from './routes/admin.departments'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminAcademicCalendarRouteImport } from './routes/admin.academic-calendar'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherTimetableRoute = TeacherTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherRoomRequestRoute = TeacherRoomRequestRouteImport.update({
  id: '/room-request',
  path: '/room-request',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResultsRoute = TeacherResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProfileRoute = TeacherProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherNoticesRoute = TeacherNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLeaveRoute = TeacherLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGradebookRoute = TeacherGradebookRouteImport.update({
  id: '/gradebook',
  path: '/gradebook',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDashboardRoute = TeacherDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentTimetableRoute = StudentTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResultsRoute = StudentResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNoticesRoute = StudentNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => StudentRoute,
} as any)
const StudentMessagesRoute = StudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLibraryRoute = StudentLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeesRoute = StudentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => StudentRoute,
} as any)
const StudentFeedbackRoute = StudentFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => StudentRoute,
} as any)
const StudentEventsRoute = StudentEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDocumentsRoute = StudentDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAttendanceRoute = StudentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentActivityRoute = StudentActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => StudentRoute,
} as any)
const AdminTimetableRoute = AdminTimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeachersRoute = AdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomApprovalsRoute = AdminRoomApprovalsRouteImport.update({
  id: '/room-approvals',
  path: '/room-approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExamsRoute = AdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentRoute = AdminEnrollmentRouteImport.update({
  id: '/enrollment',
  path: '/enrollment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentRequestsRoute = AdminDocumentRequestsRouteImport.update({
  id: '/document-requests',
  path: '/document-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDepartmentsRoute = AdminDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicCalendarRoute = AdminAcademicCalendarRouteImport.update({
  id: '/academic-calendar',
  path: '/academic-calendar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academic-calendar': typeof AdminAcademicCalendarRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/document-requests': typeof AdminDocumentRequestsRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/room-approvals': typeof AdminRoomApprovalsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/student/activity': typeof StudentActivityRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/events': typeof StudentEventsRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/gradebook': typeof TeacherGradebookRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/notices': typeof TeacherNoticesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/room-request': typeof TeacherRoomRequestRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academic-calendar': typeof AdminAcademicCalendarRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/document-requests': typeof AdminDocumentRequestsRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/room-approvals': typeof AdminRoomApprovalsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/student/activity': typeof StudentActivityRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/events': typeof StudentEventsRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/gradebook': typeof TeacherGradebookRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/notices': typeof TeacherNoticesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/room-request': typeof TeacherRoomRequestRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/academic-calendar': typeof AdminAcademicCalendarRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/departments': typeof AdminDepartmentsRoute
  '/admin/document-requests': typeof AdminDocumentRequestsRoute
  '/admin/enrollment': typeof AdminEnrollmentRoute
  '/admin/exams': typeof AdminExamsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/room-approvals': typeof AdminRoomApprovalsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/teachers': typeof AdminTeachersRoute
  '/admin/timetable': typeof AdminTimetableRoute
  '/student/activity': typeof StudentActivityRoute
  '/student/attendance': typeof StudentAttendanceRoute
  '/student/courses': typeof StudentCoursesRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/documents': typeof StudentDocumentsRoute
  '/student/events': typeof StudentEventsRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/feedback': typeof StudentFeedbackRoute
  '/student/fees': typeof StudentFeesRoute
  '/student/library': typeof StudentLibraryRoute
  '/student/messages': typeof StudentMessagesRoute
  '/student/notices': typeof StudentNoticesRoute
  '/student/results': typeof StudentResultsRoute
  '/student/timetable': typeof StudentTimetableRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/dashboard': typeof TeacherDashboardRoute
  '/teacher/gradebook': typeof TeacherGradebookRoute
  '/teacher/leave': typeof TeacherLeaveRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/notices': typeof TeacherNoticesRoute
  '/teacher/profile': typeof TeacherProfileRoute
  '/teacher/results': typeof TeacherResultsRoute
  '/teacher/room-request': typeof TeacherRoomRequestRoute
  '/teacher/timetable': typeof TeacherTimetableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/academic-calendar'
    | '/admin/audit-logs'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/document-requests'
    | '/admin/enrollment'
    | '/admin/exams'
    | '/admin/feedback'
    | '/admin/fees'
    | '/admin/notices'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/room-approvals'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/student/activity'
    | '/student/attendance'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/documents'
    | '/student/events'
    | '/student/exams'
    | '/student/feedback'
    | '/student/fees'
    | '/student/library'
    | '/student/messages'
    | '/student/notices'
    | '/student/results'
    | '/student/timetable'
    | '/teacher/attendance'
    | '/teacher/dashboard'
    | '/teacher/gradebook'
    | '/teacher/leave'
    | '/teacher/messages'
    | '/teacher/notices'
    | '/teacher/profile'
    | '/teacher/results'
    | '/teacher/room-request'
    | '/teacher/timetable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/academic-calendar'
    | '/admin/audit-logs'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/document-requests'
    | '/admin/enrollment'
    | '/admin/exams'
    | '/admin/feedback'
    | '/admin/fees'
    | '/admin/notices'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/room-approvals'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/student/activity'
    | '/student/attendance'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/documents'
    | '/student/events'
    | '/student/exams'
    | '/student/feedback'
    | '/student/fees'
    | '/student/library'
    | '/student/messages'
    | '/student/notices'
    | '/student/results'
    | '/student/timetable'
    | '/teacher/attendance'
    | '/teacher/dashboard'
    | '/teacher/gradebook'
    | '/teacher/leave'
    | '/teacher/messages'
    | '/teacher/notices'
    | '/teacher/profile'
    | '/teacher/results'
    | '/teacher/room-request'
    | '/teacher/timetable'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/student'
    | '/teacher'
    | '/admin/academic-calendar'
    | '/admin/audit-logs'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/document-requests'
    | '/admin/enrollment'
    | '/admin/exams'
    | '/admin/feedback'
    | '/admin/fees'
    | '/admin/notices'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/room-approvals'
    | '/admin/students'
    | '/admin/teachers'
    | '/admin/timetable'
    | '/student/activity'
    | '/student/attendance'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/documents'
    | '/student/events'
    | '/student/exams'
    | '/student/feedback'
    | '/student/fees'
    | '/student/library'
    | '/student/messages'
    | '/student/notices'
    | '/student/results'
    | '/student/timetable'
    | '/teacher/attendance'
    | '/teacher/dashboard'
    | '/teacher/gradebook'
    | '/teacher/leave'
    | '/teacher/messages'
    | '/teacher/notices'
    | '/teacher/profile'
    | '/teacher/results'
    | '/teacher/room-request'
    | '/teacher/timetable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/timetable': {
      id: '/teacher/timetable'
      path: '/timetable'
      fullPath: '/teacher/timetable'
      preLoaderRoute: typeof TeacherTimetableRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/room-request': {
      id: '/teacher/room-request'
      path: '/room-request'
      fullPath: '/teacher/room-request'
      preLoaderRoute: typeof TeacherRoomRequestRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/results': {
      id: '/teacher/results'
      path: '/results'
      fullPath: '/teacher/results'
      preLoaderRoute: typeof TeacherResultsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/profile': {
      id: '/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof TeacherProfileRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/notices': {
      id: '/teacher/notices'
      path: '/notices'
      fullPath: '/teacher/notices'
      preLoaderRoute: typeof TeacherNoticesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/leave': {
      id: '/teacher/leave'
      path: '/leave'
      fullPath: '/teacher/leave'
      preLoaderRoute: typeof TeacherLeaveRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/gradebook': {
      id: '/teacher/gradebook'
      path: '/gradebook'
      fullPath: '/teacher/gradebook'
      preLoaderRoute: typeof TeacherGradebookRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/dashboard': {
      id: '/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof TeacherDashboardRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/timetable': {
      id: '/student/timetable'
      path: '/timetable'
      fullPath: '/student/timetable'
      preLoaderRoute: typeof StudentTimetableRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/results': {
      id: '/student/results'
      path: '/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof StudentResultsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notices': {
      id: '/student/notices'
      path: '/notices'
      fullPath: '/student/notices'
      preLoaderRoute: typeof StudentNoticesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/messages': {
      id: '/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof StudentMessagesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/library': {
      id: '/student/library'
      path: '/library'
      fullPath: '/student/library'
      preLoaderRoute: typeof StudentLibraryRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/fees': {
      id: '/student/fees'
      path: '/fees'
      fullPath: '/student/fees'
      preLoaderRoute: typeof StudentFeesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/feedback': {
      id: '/student/feedback'
      path: '/feedback'
      fullPath: '/student/feedback'
      preLoaderRoute: typeof StudentFeedbackRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/events': {
      id: '/student/events'
      path: '/events'
      fullPath: '/student/events'
      preLoaderRoute: typeof StudentEventsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/documents': {
      id: '/student/documents'
      path: '/documents'
      fullPath: '/student/documents'
      preLoaderRoute: typeof StudentDocumentsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/attendance': {
      id: '/student/attendance'
      path: '/attendance'
      fullPath: '/student/attendance'
      preLoaderRoute: typeof StudentAttendanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/activity': {
      id: '/student/activity'
      path: '/activity'
      fullPath: '/student/activity'
      preLoaderRoute: typeof StudentActivityRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/timetable': {
      id: '/admin/timetable'
      path: '/timetable'
      fullPath: '/admin/timetable'
      preLoaderRoute: typeof AdminTimetableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teachers': {
      id: '/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AdminTeachersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/room-approvals': {
      id: '/admin/room-approvals'
      path: '/room-approvals'
      fullPath: '/admin/room-approvals'
      preLoaderRoute: typeof AdminRoomApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exams': {
      id: '/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AdminExamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollment': {
      id: '/admin/enrollment'
      path: '/enrollment'
      fullPath: '/admin/enrollment'
      preLoaderRoute: typeof AdminEnrollmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/document-requests': {
      id: '/admin/document-requests'
      path: '/document-requests'
      fullPath: '/admin/document-requests'
      preLoaderRoute: typeof AdminDocumentRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/departments': {
      id: '/admin/departments'
      path: '/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AdminDepartmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academic-calendar': {
      id: '/admin/academic-calendar'
      path: '/academic-calendar'
      fullPath: '/admin/academic-calendar'
      preLoaderRoute: typeof AdminAcademicCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAcademicCalendarRoute: typeof AdminAcademicCalendarRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDepartmentsRoute: typeof AdminDepartmentsRoute
  AdminDocumentRequestsRoute: typeof AdminDocumentRequestsRoute
  AdminEnrollmentRoute: typeof AdminEnrollmentRoute
  AdminExamsRoute: typeof AdminExamsRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoomApprovalsRoute: typeof AdminRoomApprovalsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTeachersRoute: typeof AdminTeachersRoute
  AdminTimetableRoute: typeof AdminTimetableRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicCalendarRoute: AdminAcademicCalendarRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDepartmentsRoute: AdminDepartmentsRoute,
  AdminDocumentRequestsRoute: AdminDocumentRequestsRoute,
  AdminEnrollmentRoute: AdminEnrollmentRoute,
  AdminExamsRoute: AdminExamsRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoomApprovalsRoute: AdminRoomApprovalsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTeachersRoute: AdminTeachersRoute,
  AdminTimetableRoute: AdminTimetableRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentActivityRoute: typeof StudentActivityRoute
  StudentAttendanceRoute: typeof StudentAttendanceRoute
  StudentCoursesRoute: typeof StudentCoursesRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentDocumentsRoute: typeof StudentDocumentsRoute
  StudentEventsRoute: typeof StudentEventsRoute
  StudentExamsRoute: typeof StudentExamsRoute
  StudentFeedbackRoute: typeof StudentFeedbackRoute
  StudentFeesRoute: typeof StudentFeesRoute
  StudentLibraryRoute: typeof StudentLibraryRoute
  StudentMessagesRoute: typeof StudentMessagesRoute
  StudentNoticesRoute: typeof StudentNoticesRoute
  StudentResultsRoute: typeof StudentResultsRoute
  StudentTimetableRoute: typeof StudentTimetableRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentActivityRoute: StudentActivityRoute,
  StudentAttendanceRoute: StudentAttendanceRoute,
  StudentCoursesRoute: StudentCoursesRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentDocumentsRoute: StudentDocumentsRoute,
  StudentEventsRoute: StudentEventsRoute,
  StudentExamsRoute: StudentExamsRoute,
  StudentFeedbackRoute: StudentFeedbackRoute,
  StudentFeesRoute: StudentFeesRoute,
  StudentLibraryRoute: StudentLibraryRoute,
  StudentMessagesRoute: StudentMessagesRoute,
  StudentNoticesRoute: StudentNoticesRoute,
  StudentResultsRoute: StudentResultsRoute,
  StudentTimetableRoute: StudentTimetableRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherDashboardRoute: typeof TeacherDashboardRoute
  TeacherGradebookRoute: typeof TeacherGradebookRoute
  TeacherLeaveRoute: typeof TeacherLeaveRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherNoticesRoute: typeof TeacherNoticesRoute
  TeacherProfileRoute: typeof TeacherProfileRoute
  TeacherResultsRoute: typeof TeacherResultsRoute
  TeacherRoomRequestRoute: typeof TeacherRoomRequestRoute
  TeacherTimetableRoute: typeof TeacherTimetableRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherDashboardRoute: TeacherDashboardRoute,
  TeacherGradebookRoute: TeacherGradebookRoute,
  TeacherLeaveRoute: TeacherLeaveRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherNoticesRoute: TeacherNoticesRoute,
  TeacherProfileRoute: TeacherProfileRoute,
  TeacherResultsRoute: TeacherResultsRoute,
  TeacherRoomRequestRoute: TeacherRoomRequestRoute,
  TeacherTimetableRoute: TeacherTimetableRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
